# Generated by Django 4.2 on 2023-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_goods_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
