# Generated by Django 4.2 on 2023-05-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_status", "0001_initial"),
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_number",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("pharmacy", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("SELF", "Self"), ("DELIVERY", "Delivery")],
                        default="DELIVERY",
                        max_length=100,
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comment", models.TextField()),
                ("paid", models.BooleanField(default=False)),
                ("paid_delivery", models.BooleanField(default=False)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("was_paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.goods"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(through="orders.OrderItem", to="goods.goods"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="order_status.orderstatus",
            ),
        ),
    ]
