# Generated by Django 4.2 on 2023-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_total_price_alter_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("IN_PLACE", "In_place")],
                default="ONLINE",
                max_length=100,
            ),
        ),
    ]
